import datetime
current_time = datetime.datetime.now()
print("Print your input")
print("Day :", current_time.day)
print("Month :", current_time.month)
print("Year:", current_time.year)
print("Hour :", current_time.hour)
print("Minute :", current_time.minute)
print("Second :", current_time.second)
print("Microsecond :", current_time.microsecond)